services:
  - type: web
    name: resumecraft-2025
    env: docker
    plan: starter
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: PORT
        value: 3000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: NEXT_PUBLIC_CSHARP_PDF_API
        value: https://resumecraft-2025.onrender.com/generate-pdf
